(require 'package)

;; define the package repos
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")
			 ("melpa" . "https://melpa.milkbox.net/packages/")))
;; some crazy bug
;; correction here https://emacs.stackexchange.com/questions/51721/failed-to-download-gnu-archive
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

;; start processing pacakages
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)

;; load the actual literate org file that contains the configuration
(require 'org)
(org-babel-load-file "~/.emacs.d/config.org")

;;; AUTOGENERATED
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (lsp-java lsp-mode evil-org org-ref evil-magit magit use-package flycheck-haskell zenburn-theme jdee meghanada counsel auctex-latexmk auctex org-evil evil-surround evil-escape))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

